### ISSUE TITLE
Squids won't drop squids

### ISSUE THREAD

**Issue by HTPSTheFreezingCold** [Nyancatpig/Cultural-Delights-1.18.2#43]
I'm running into a problem with squids we keep killing squids, with and without looting, and they won't drop any squids just ink sacks. The other foods in the mod work fine but I can't get squids to drop the squid

**Comment by Grimalakin** [comment]
Same issue... but it only seems to occur when the mod is being run on a server
a singleplayer world, even when opened to a LAN, drops the squid as intended

(edit)
forgot to add the _More Mob Heads_ datapack from Vanilla Tweaks to my testing world. as soon as I did, the "bug" happened
I guess it's a loot table conflict.

**Comment by HTPSTheFreezingCold** [comment]
On my server we also have a more mob heads datapack so I think that is the problem since that seems to be the common factor with the bug

**Comment by Nyancatpig** [comment]
Cultural Delights overwrites the squid loot table to make it drop the squid item.
If More Mob Heads also overwrites the loot table to drop the head items, then that is why this issue is occuring.
You can fix this by modifying the More Mob Heads datapack so that the squid loot table drops both the head and the squid item.
